// <auto-generated />
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Text.Json;

namespace Ensure.Examples.xUnit.DataValidation
{
    public abstract class UserDataValidationStepsBase
    {

        /// <summary>
        /// When I validate multiple users data
        /// </summary>
        public abstract Task WhenIValidateMultipleUsersData(List<Dictionary<string, string>> tableData);

        /// <summary>
        /// Then all users should be valid
        /// </summary>
        public abstract Task ThenAllUsersShouldBeValid();

        /// <summary>
        /// Then validation should fail with \"Invalid age and email format\"
        /// </summary>
        public abstract Task ThenValidationShouldFailWith(string param1);

    }
}
